version: "3.3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    # volumes:
    #   - ./:/usr/src/app/

  postgres:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Uto@00574
      - POSTGRES_DB=alcohol
    ports:
      # Standard port for PostgreSQL databases
      - "5432:5432"
    volumes:
      # When the PostgresSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      - ./alcohol.sql:/docker-entrypoint-initdb.d/alcohol.sql
